version: '3.8'

services:
  router-mqtt-publisher:
    image: rafavg77/router-mqtt-publisher:latest
    environment:
      - ROUTER_IP=${ROUTER_IP}
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC_CONFIG_PREFIX=${MQTT_TOPIC_CONFIG_PREFIX}
      - MQTT_TOPIC_DATA_PREFIX=${MQTT_TOPIC_DATA_PREFIX}
    restart: unless-stopped