services:
  router-mqtt-publisher:
    image: rafavg77/router-mqtt-publisher:latest # Jala la imagen desde Docker Hub
    container_name: router_mqtt_publisher       # Opcional: nombre específico para el contenedor
    restart: unless-stopped
    environment:
      - ROUTER_IP=${ROUTER_IP}
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC_CONFIG_PREFIX=${MQTT_TOPIC_CONFIG_PREFIX}
      - MQTT_TOPIC_DATA_PREFIX=${MQTT_TOPIC_DATA_PREFIX}
      - EXECUTION_INTERVAL=${EXECUTION_INTERVAL}
      - LOKI_URL=${LOKI_URL}
      - PUID=1000
      - PGID=1000
      - TZ=America/Monterrey